### ISSUE TITLE
Which package do you want?

### ISSUE THREAD

**Issue by alirezabashi98** [icodeyou/hello_riverpod#3]
Prerequisites: Make sure that the following CLI are installed:
flutter, very_good, mason, gh

This is the text that is said after execution and I go to the end, the folder is not created and the following message is given

We have an error!
⚠️ This folder is about to be deleted : /home/alireza/StudioProjects/test/hello_riverpod/HELLOWORLDS/ex
Do you want to delete it? Press enter to confirm, type NO if you want to keep it:

I think it's from gh, I don't know what to install

**Comment by alirezabashi98** [comment]
I read the code and came to the following code

brew install gh

I understand that it is github-cli

https://cli.github.com/manual/installation

For Linux, you can directly go to the link below

https://github.com/cli/cli/blob/trunk/docs/install_linux.md

For the release version, go to the link below

https://github.com/cli/cli/releases/tag/v2.27.0

I went to check that very_good_cli was not installed and it gave the following error

Package very_good_cli is currently active at version 0.13.0.
The very_good_cli package is already activated at the newest available version.
To recompile executables, first run `dart pub global deactivate very_good_cli`.
Installed executable very_good.
Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

   export PATH="$PATH":"$HOME/.pub-cache/bin"

Activated very_good_cli 0.13.0.


It was fixed with the following command

   export PATH="$PATH":"$HOME/.pub-cache/bin"

And the problem is solved and it works

**Comment by icodeyou** [comment]
Thank you @alirezabashi98 
Would you like me to update the documentation in README.md, concerning the different CLI to install ?
